name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter (3.29.2)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Get dependencies
        run: cd src/top_app && flutter pub get

      - name: Generate code (build_runner)
        run: cd src/top_app && flutter pub run build_runner build --delete-conflicting-outputs