name: Flutter CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Change directory and get dependencies
        run: cd src/top_app && flutter pub get

      - name: Build APK
        run: cd src/top_app && flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: src/top_app/build/app/outputs/flutter-apk/app-release.apk