name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Change directory to Flutter app
        run: cd src/top_app && flutter pub get

      - name: Analyze code
        run: cd src/top_app && flutter analyze

      - name: Generate code (build_runner)
        run: cd src/top_app && flutter pub run build_runner build --delete-conflicting-outputs